"""create clients table

Revision ID: 211ade466f68
Revises: 60a0af0b875d
Create Date: 2026-04-05 18:46:11.948222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211ade466f68'
down_revision: Union[str, Sequence[str], None] = '60a0af0b875d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=15), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_invoices', sa.Integer(), nullable=True),
    sa.Column('paid_invoices', sa.Integer(), nullable=True),
    sa.Column('overdue_invoices', sa.Integer(), nullable=True),
    sa.Column('disputed_invoices', sa.Integer(), nullable=True),
    sa.Column('avg_payment_delay_days', sa.Integer(), nullable=True),
    sa.Column('total_billed', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
