"""create expenses table

Revision ID: 48b4800d970f
Revises: 667f819969f8
Create Date: 2026-04-05 17:32:49.225624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48b4800d970f'
down_revision: Union[str, Sequence[str], None] = '667f819969f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('category', sa.Enum('EQUIPMENT', 'SOFTWARE', 'INTERNET', 'TRAVEL', 'COWORKING', 'EDUCATION', 'MARKETING', 'UTILITIES', 'FOOD', 'OTHER', name='expensecategory'), nullable=True),
    sa.Column('is_tax_deductible', sa.Boolean(), nullable=True),
    sa.Column('gst_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vendor_name', sa.String(length=100), nullable=True),
    sa.Column('invoice_reference', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
